### ISSUE TITLE
Shall I install `LDHP-builder`?

### ISSUE THREAD

**Issue by LePingKYXK** [WillBaldwin0/LDHP-builder#1]
Hi, 
I just found this `LDHP-builder` python project from your paper `arXiv:2403.06955v1`, and I would like to try your script to build hybrid organic-inorganic perovskites, e.g. (PEA) _2_ (MA) _n-1_ Pb _n_ I _3n+1_ , (n = 1 to 4). 

However, two questions hinder me.

1) I did not find a way to import the `LDHPbuilder` since there is no setup module (I have installed the `ase`, `numpy`, `scipy`, and `aseMolec` modules as suggested in the **Dependencies** section).

2) As described in the `README`, 
```python
pb = PerovskiteBuilder()

samples = pb.generate_homogeneous_perovskite_samples( # homogeneous since just one kind of molecule
    monolayer, 
    molecule, 
    num_layers=2, # should be a power of 2, but 4 already implies a very large search task
    num_samples=10, 
    max_num_attempts=15, 
    stacking_method='total_thickness' # this can be either 'total_thickness' or 'half_thickness'. use half_thickness for long, thin +1 molecules
)
```
I was wondering if the parameter `num_layers` means the number of layers of BX3 octahedra. If so, could it be 1, or 3? Since `num_layers=2, # should be a power of 2, but 4 already implies a very large search task`, it seems that this parameter only deals with n^2, if my understanding is correct. 

It would be greatly appreciated if you could reply.

All the best,
Huan

**Comment by WillBaldwin0** [comment]
Hi Huan, 

Great to hear that you’d like to use our package!

For installation, if you want to use it right now I you can add the package dir to path. I will add a `setup.py` today so that you can install with pip too. 

At the moment we are only supporting perovskite with no 3d regions (i.e. a single layer of PbX octahedra). `num_layers` is more like a doubling of the unit cell in the out-of-plane direction. This number can be 1, but not 3, due to the symmetry constraints on how we generate the structures. If you see figure 8 in our preprint, that shows an example with `num_layers=2`. 

I will make a separate issue for kind of layers you describe with n in (PEA) 2 (MA) n-1 Pb n I 3n+1 , (n = 1 to 4).

**Comment by WillBaldwin0** [comment]
You should now be able to install with pip. The `aseMolec` is not currently on PyPI, so must be installed separately. 49df71195beafd6111f7522425771b4c75c1ca26
